name: CI
on:
  push:
    branches:
    - main
  pull_request:
jobs:
  build:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./tests/CI/run-unit-test
