name: Run integration tests
on:
  workflow_dispatch:
    inputs:
      SHA:
        description: 'SHA to run test on'
        required: true
jobs:
  run-integration-tests:
    name: Integration tests
    runs-on: ubuntu-latest
    container: mbedos/mbed-os-env:latest
    steps:
      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y lavacli curl

      - name: Set GitHub checks pending
        uses: LouisBrunner/checks-action@v1.1.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: launch lava job
          status: in_progress

      - name: Run lava job
        env:
          LAVA_SERVER_TOKEN: ${{ secrets.LAVA_SERVER_TOKEN }}
          LAVA_SERVER_URL: ${{ secrets.LAVA_SERVER_URL }}
          USER_TOKEN: ${{ secrets.USER_TOKEN }}
          REPOSITORY: ${{ github.repository }}
        run: |
          SHA=${{ github.event.inputs.SHA }}
          echo "Running job for SHA $SHA"
          git clone https://github.com/ARMmbed/mbed-os-lava-scripts.git mbed-os-lava-scripts

          # log in our lavacli
          lavacli identities add --uri "$LAVA_SERVER_URL" --username lava-admin --token "$LAVA_SERVER_TOKEN" default

          # prepare the job definition and submit it
          cd mbed-os-lava-scripts/jobs
          LAVA_JOB_NO=`./launch_job.sh services_test.yaml ${REPOSITORY} ${SHA} ${USER_TOKEN}`
          echo "Running lava job $LAVA_JOB_NO"
          cd ../..

          # wait for job to finish grab the log and filter secrets
          lavacli jobs wait $LAVA_JOB_NO
          echo "lava job $LAVA_JOB_NO completed"
          lavacli jobs logs $LAVA_JOB_NO > ble-services-integration-test.log
          sed -i "s/${{ secrets.USER_TOKEN }}/==USER_TOKEN==/" ble-services-integration-test.log
          sed -i "s/${{ secrets.LAVA_SERVER_TOKEN }}/==LAVA_SERVER_TOKEN==/" ble-services-integration-test.log

          # get test result
          LAVA_TEST_RESULT="failure"
          JOB_RESULT=`lavacli jobs show $LAVA_JOB_NO | grep Health | cut -d':' -f 2 | xargs`
          if [ $JOB_RESULT = Complete ]; then LAVA_TEST_RESULT="success"; fi
          # store value between steps
          echo "lava_result=${LAVA_TEST_RESULT}" >> $GITHUB_ENV

          # show the log in workflow
          printf "\n\n---------------------------- LAVA log ----------------------------------\n\n"
          cat ble-services-integration-test.log
          printf "\n\n---------------------------- LAVA log end ------------------------------\n\n"

      - name: Set GitHub Checks complete
        uses: LouisBrunner/checks-action@v1.1.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: launch lava job
          status: completed
          conclusion: ${{ env.lava_result }}

      - name: Upload integration test logs
        uses: actions/upload-artifact@v2.2.3
        with:
          name: integration-test-log
          path: ble-services-integration-test.log

